import {
  mdiAlertCircleOutline,
  mdiArrowULeftBottom,
  mdiCheckCircleOutline,
  mdiDeleteOutline,
  mdiDotsVertical,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFolderOpen,
  mdiFormatBold,
  mdiFormatItalic,
  mdiLinkVariant,
  mdiMenu,
  mdiSquareEditOutline,
  mdiWindowClose,
} from '@mdi/js';
import { aliases } from 'vuetify/iconsets/mdi-svg';

export default {
  ...aliases,
  mdiSquareEditOutline,
  mdiWindowClose,
  mdiFolderOpen,
  mdiMenu,
  mdiDeleteOutline,
  mdiDotsVertical,
  mdiAlertCircleOutline,
  mdiCheckCircleOutline,
  mdiArrowULeftBottom,
  mdiFormatBold,
  mdiFormatItalic,
  mdiLinkVariant,
  mdiEyeOutline,
  mdiEyeOffOutline,
};
