export enum AppRoutes {
  Main = 'main',
  Auth = 'auth',
  SignIn = 'signIn',
  ResetPassword = 'resetPassword',
  NewPassword = 'newPassword',
  About = 'about',
  Events = 'events',
  Gallery = 'gallery',
  Partners = 'partners',
  Social = 'social',
  Contacts = 'contacts',
  Accounts = 'accounts',
  InProgress = 'inProgress',
}
